# Generated by Django 4.0.1 on 2022-01-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('product_description', models.TextField()),
                ('product_image_1', models.ImageField(upload_to='.s/assets/images/')),
                ('product_image_2', models.ImageField(upload_to='.s/assets/images/')),
                ('product_image_3', models.ImageField(upload_to='.s/assets/images/')),
                ('product_category', models.CharField(choices=[('Vegetables', 'vegetables'), ('Fruits', 'fruits'), ('Eggs', 'eggs'), ('Milk', 'milk'), ('Honey', 'honey'), ('Trees', 'trees'), ('Wheat', 'wheat'), ('Maize', 'maize')], max_length=15)),
                ('product_amount', models.CharField(max_length=30)),
                ('available_location', models.CharField(max_length=30)),
                ('date_posted', models.DateTimeField()),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
    ]
